### ISSUE TITLE
HTTP Resources - Inconsistent data wrapping

### ISSUE THREAD

**Issue by liam-oconnor-envirovue** [emargareten/inertia-modal#20] opened 2024-02-13 10:10 UTC
I have a route, `/users/5/edit` and pass the user into the modal as a prop using an HTTP Resource.

```php
public function __invoke(User $user)
{
    return Inertia::modal('User/Edit')
        ->with([
            'user' => new UserResource($user),
        ])
        ->baseRoute('users.index');
}
```

If I go directly to the user edit page the user is wrapped in a "data" property. However, if I create an inertia link to open the user edit modal the user data is NOT wrapped in the data property.

When trying to figure out the problem myself I noticed the `renderModal` function in `Emargareten\InertiaModal\Modal` is only used when I click the inertia link and is not fired when I go directly to the edit user page.

**Comment by emargareten** [comment] 2024-02-13 19:25
Can't reproduce.
@liam-oconnor-envirovue can you create a minimal repo where I can see this?

**Comment by emargareten** [comment] 2024-02-25 09:03
Closing as unable to reproduce. Feel free to open a new issue if the problem persists or if you have additional details.

**Closed by emargareten** 2024-02-25 09:03 UTC
